name: 'Terraform Deploy'

on:
  push:
    paths:
      - infra/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Init Terraform
        run: terraform init
        working-directory: ./infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./infra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./infra
